create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  primary_muscle text not null,
  secondary_muscle text,
  is_strength_exercise integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.user_exercise_preferences (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  enabled integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, exercise_id)
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_date date not null,
  notes text,
  machine_profile_id text,
  created_at timestamptz not null default now()
);

alter table public.workout_sessions add column if not exists machine_profile_id text;

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_id bigint not null references public.workout_sessions(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  set_number integer not null,
  reps integer not null,
  weight numeric not null,
  rir numeric,
  is_warmup boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.workout_sets add column if not exists is_warmup boolean not null default false;

create table if not exists public.body_weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  weight numeric not null,
  logged_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, logged_date)
);

create table if not exists public.muscle_strength_config (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  muscle_group text not null,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  weight_factor numeric not null default 1.0
);

create table if not exists public.app_settings (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  user_low uuid generated always as (least(requester_id, addressee_id)) stored,
  user_high uuid generated always as (greatest(requester_id, addressee_id)) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id),
  unique (user_low, user_high)
);

create table if not exists public.friend_invites (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  accepted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.leaderboard_score_snapshots (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  exercise_name text not null,
  best_score numeric not null,
  best_sets jsonb not null default '[]'::jsonb,
  achieved_at date not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, exercise_id)
);

alter table public.leaderboard_score_snapshots
  add column if not exists best_sets jsonb not null default '[]'::jsonb;

create table if not exists public.shared_training_splits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  split_days jsonb not null,
  updated_by uuid references auth.users(id) on delete set null,
  updated_by_name text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.split_sync_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  user_low uuid generated always as (least(requester_id, addressee_id)) stored,
  user_high uuid generated always as (greatest(requester_id, addressee_id)) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id),
  unique (user_low, user_high)
);

alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.user_exercise_preferences enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;
alter table public.body_weight_logs enable row level security;
alter table public.muscle_strength_config enable row level security;
alter table public.app_settings enable row level security;
alter table public.friendships enable row level security;
alter table public.friend_invites enable row level security;
alter table public.leaderboard_score_snapshots enable row level security;
alter table public.shared_training_splits enable row level security;
alter table public.split_sync_requests enable row level security;

drop policy if exists "profiles are visible to their owner" on public.profiles;
drop policy if exists "profiles can be inserted by their owner" on public.profiles;
drop policy if exists "profiles can be updated by their owner" on public.profiles;
drop policy if exists "exercises are owned by their user" on public.exercises;
drop policy if exists "standard exercises are readable by authenticated users" on public.exercises;
drop policy if exists "exercise preferences are owned by their user" on public.user_exercise_preferences;
drop policy if exists "workout sessions are owned by their user" on public.workout_sessions;
drop policy if exists "workout sets are owned by their user" on public.workout_sets;
drop policy if exists "workout sessions are visible to accepted friends" on public.workout_sessions;
drop policy if exists "workout sets are visible to accepted friends" on public.workout_sets;
drop policy if exists "body weight logs are owned by their user" on public.body_weight_logs;
drop policy if exists "muscle configs are owned by their user" on public.muscle_strength_config;
drop policy if exists "settings are owned by their user" on public.app_settings;
drop policy if exists "profiles are visible to accepted friends" on public.profiles;
drop policy if exists "friendships are visible to participants" on public.friendships;
drop policy if exists "friendships can be created by participants" on public.friendships;
drop policy if exists "friendships can be updated by participants" on public.friendships;
drop policy if exists "friendships can be deleted by participants" on public.friendships;
drop policy if exists "friend invites are owned by their user" on public.friend_invites;
drop policy if exists "score snapshots are visible to friends" on public.leaderboard_score_snapshots;
drop policy if exists "score snapshots are owned by their user" on public.leaderboard_score_snapshots;
drop policy if exists "training splits are visible to their user" on public.shared_training_splits;
drop policy if exists "split sync requests are visible to participants" on public.split_sync_requests;

create policy "profiles are visible to their owner" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles are visible to accepted friends" on public.profiles
  for select using (
    auth.uid() is not null
    and exists (
      select 1
      from public.friendships
      where status = 'accepted'
        and (
          (requester_id = auth.uid() and addressee_id = profiles.id)
          or (addressee_id = auth.uid() and requester_id = profiles.id)
        )
    )
  );

create policy "profiles can be inserted by their owner" on public.profiles
  for insert with check (auth.uid() = id);

create policy "profiles can be updated by their owner" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "standard exercises are readable by authenticated users" on public.exercises
  for select using (auth.role() = 'authenticated');

create policy "exercise preferences are owned by their user" on public.user_exercise_preferences
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sessions are owned by their user" on public.workout_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sets are owned by their user" on public.workout_sets
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sessions are visible to accepted friends" on public.workout_sessions
  for select using (
    exists (
      select 1
      from public.friendships
      where status = 'accepted'
        and (
          (requester_id = auth.uid() and addressee_id = workout_sessions.user_id)
          or (addressee_id = auth.uid() and requester_id = workout_sessions.user_id)
        )
    )
  );

create policy "workout sets are visible to accepted friends" on public.workout_sets
  for select using (
    exists (
      select 1
      from public.friendships
      where status = 'accepted'
        and (
          (requester_id = auth.uid() and addressee_id = workout_sets.user_id)
          or (addressee_id = auth.uid() and requester_id = workout_sets.user_id)
        )
    )
  );

create policy "body weight logs are owned by their user" on public.body_weight_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "muscle configs are owned by their user" on public.muscle_strength_config
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "settings are owned by their user" on public.app_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "friendships are visible to participants" on public.friendships
  for select using (auth.uid() in (requester_id, addressee_id));

create policy "friendships can be created by participants" on public.friendships
  for insert with check (auth.uid() in (requester_id, addressee_id));

create policy "friendships can be updated by participants" on public.friendships
  for update using (auth.uid() in (requester_id, addressee_id)) with check (auth.uid() in (requester_id, addressee_id));

create policy "friendships can be deleted by participants" on public.friendships
  for delete using (auth.uid() in (requester_id, addressee_id));

create policy "friend invites are owned by their user" on public.friend_invites
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create policy "score snapshots are visible to friends" on public.leaderboard_score_snapshots
  for select using (
    auth.uid() = user_id
    or exists (
      select 1
      from public.friendships
      where status = 'accepted'
        and (
          (requester_id = auth.uid() and addressee_id = leaderboard_score_snapshots.user_id)
          or (addressee_id = auth.uid() and requester_id = leaderboard_score_snapshots.user_id)
        )
    )
  );

create policy "score snapshots are owned by their user" on public.leaderboard_score_snapshots
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "training splits are visible to their user" on public.shared_training_splits
  for select using (auth.uid() = user_id);

create policy "split sync requests are visible to participants" on public.split_sync_requests
  for select using (auth.uid() in (requester_id, addressee_id));

drop index if exists exercises_user_id_idx;
create unique index if not exists exercises_name_idx on public.exercises(name);
create index if not exists user_exercise_preferences_user_id_idx on public.user_exercise_preferences(user_id);
create index if not exists user_exercise_preferences_exercise_id_idx on public.user_exercise_preferences(exercise_id);
create index if not exists workout_sessions_user_id_date_idx on public.workout_sessions(user_id, workout_date desc);
create index if not exists workout_sets_user_id_created_idx on public.workout_sets(user_id, created_at, set_number);
create index if not exists workout_sets_session_id_idx on public.workout_sets(session_id);
create index if not exists workout_sets_exercise_id_idx on public.workout_sets(exercise_id);
create index if not exists body_weight_logs_user_id_date_idx on public.body_weight_logs(user_id, logged_date desc);
create index if not exists friendships_requester_id_idx on public.friendships(requester_id);
create index if not exists friendships_addressee_id_idx on public.friendships(addressee_id);
create index if not exists friend_invites_owner_id_idx on public.friend_invites(owner_id);
create index if not exists friend_invites_token_idx on public.friend_invites(token);
create index if not exists leaderboard_score_snapshots_exercise_score_idx on public.leaderboard_score_snapshots(exercise_id, best_score desc);
create index if not exists shared_training_splits_updated_at_idx on public.shared_training_splits(updated_at desc);
create index if not exists split_sync_requests_requester_id_idx on public.split_sync_requests(requester_id);
create index if not exists split_sync_requests_addressee_id_idx on public.split_sync_requests(addressee_id);

create or replace function public.profile_exists_for_email(lookup_email text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where lower(email) = lower(lookup_email)
  );
$$;

grant execute on function public.profile_exists_for_email(text) to anon, authenticated;

create or replace function public.accept_friend_invite(invite_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  invite_row public.friend_invites%rowtype;
  accepting_user uuid := auth.uid();
begin
  if accepting_user is null then
    raise exception 'Please log in again.';
  end if;

  select *
  into invite_row
  from public.friend_invites
  where token = invite_token
    and accepted_by is null
    and expires_at > now()
  limit 1;

  if invite_row.id is null then
    raise exception 'This invite is expired or has already been used.';
  end if;

  if invite_row.owner_id = accepting_user then
    raise exception 'You cannot accept your own invite.';
  end if;

  insert into public.friendships (requester_id, addressee_id, status)
  values (invite_row.owner_id, accepting_user, 'accepted')
  on conflict (user_low, user_high)
  do update set status = 'accepted', updated_at = now();

  update public.friend_invites
  set accepted_by = accepting_user
  where id = invite_row.id;
end;
$$;

grant execute on function public.accept_friend_invite(text) to authenticated;

create or replace function public.request_split_sync(friend_id uuid, split_days jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  editing_user uuid := auth.uid();
  editor_name text;
begin
  if editing_user is null then
    raise exception 'Please log in again.';
  end if;

  if jsonb_typeof(split_days) <> 'array' then
    raise exception 'Training split days must be an array.';
  end if;

  if not exists (
    select 1
    from public.friendships
    where status = 'accepted'
      and (
        (requester_id = editing_user and addressee_id = friend_id)
        or (addressee_id = editing_user and requester_id = friend_id)
      )
  ) then
    raise exception 'Split synchronization can only be requested from an accepted friend.';
  end if;

  select coalesce(nullif(trim(name), ''), split_part(email, '@', 1), 'User')
  into editor_name
  from public.profiles
  where id = editing_user;

  insert into public.shared_training_splits (user_id, split_days, updated_by, updated_by_name, updated_at)
  values (editing_user, split_days, editing_user, coalesce(editor_name, 'User'), now())
  on conflict (user_id) do nothing;

  insert into public.split_sync_requests (requester_id, addressee_id, status, updated_at)
  values (editing_user, friend_id, 'pending', now())
  on conflict (user_low, user_high)
  do update set
    requester_id = excluded.requester_id,
    addressee_id = excluded.addressee_id,
    status = 'pending',
    updated_at = excluded.updated_at;
end;
$$;

grant execute on function public.request_split_sync(uuid, jsonb) to authenticated;

create or replace function public.respond_split_sync(request_id uuid, accept_request boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  receiving_user uuid := auth.uid();
  request_row public.split_sync_requests%rowtype;
begin
  if receiving_user is null then
    raise exception 'Please log in again.';
  end if;

  select *
  into request_row
  from public.split_sync_requests
  where id = request_id
    and addressee_id = receiving_user
    and status = 'pending';

  if request_row.id is null then
    raise exception 'This split synchronization request is not available.';
  end if;

  update public.split_sync_requests
  set status = case when accept_request then 'accepted' else 'declined' end,
      updated_at = now()
  where id = request_id;

  if accept_request then
    insert into public.shared_training_splits (user_id, split_days, updated_by, updated_by_name, updated_at)
    select receiving_user, split_days, updated_by, updated_by_name, updated_at
    from public.shared_training_splits
    where user_id = request_row.requester_id
    on conflict (user_id)
    do update set
      split_days = excluded.split_days,
      updated_by = excluded.updated_by,
      updated_by_name = excluded.updated_by_name,
      updated_at = excluded.updated_at;
  end if;
end;
$$;

grant execute on function public.respond_split_sync(uuid, boolean) to authenticated;

create or replace function public.remove_split_sync(friend_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Please log in again.';
  end if;

  delete from public.split_sync_requests
  where (requester_id = current_user_id and addressee_id = friend_id)
     or (addressee_id = current_user_id and requester_id = friend_id);
end;
$$;

grant execute on function public.remove_split_sync(uuid) to authenticated;

create or replace function public.save_shared_training_split(split_days jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  editing_user uuid := auth.uid();
  editor_name text;
begin
  if editing_user is null then
    raise exception 'Please log in again.';
  end if;

  if jsonb_typeof(split_days) <> 'array' then
    raise exception 'Training split days must be an array.';
  end if;

  select coalesce(nullif(trim(name), ''), split_part(email, '@', 1), 'User')
  into editor_name
  from public.profiles
  where id = editing_user;

  insert into public.shared_training_splits (user_id, split_days, updated_by, updated_by_name, updated_at)
  with recursive synchronized_users(user_id) as (
    select editing_user
    union
    select case when request.requester_id = group_user.user_id then request.addressee_id else request.requester_id end
    from synchronized_users group_user
    join public.split_sync_requests request
      on request.status = 'accepted'
      and group_user.user_id in (request.requester_id, request.addressee_id)
  )
  select user_id, split_days, editing_user, coalesce(editor_name, 'User'), now()
  from synchronized_users
  on conflict (user_id)
  do update set
    split_days = excluded.split_days,
    updated_by = excluded.updated_by,
    updated_by_name = excluded.updated_by_name,
    updated_at = excluded.updated_at;
end;
$$;

grant execute on function public.save_shared_training_split(jsonb) to authenticated;

grant select on public.exercises to authenticated;
grant select, insert, update, delete on public.user_exercise_preferences to authenticated;
grant select, insert, update, delete on public.friendships to authenticated;
grant select, insert, update, delete on public.friend_invites to authenticated;
grant select, insert, update, delete on public.leaderboard_score_snapshots to authenticated;
grant select on public.shared_training_splits to authenticated;
grant select on public.split_sync_requests to authenticated;

insert into public.exercises (name, primary_muscle, secondary_muscle, is_strength_exercise) values
  ('Barbell Bench Press', 'Chest', null, 0),
  ('Incline Barbell Bench Press', 'Chest', null, 0),
  ('Dumbbell Bench Press', 'Chest', null, 0),
  ('Incline Dumbbell Press', 'Chest', null, 0),
  ('Machine Chest Press', 'Chest', null, 0),
  ('Weighted Dip', 'Chest', 'Triceps', 0),
  ('Cable Fly', 'Chest', null, 0),
  ('High to Low Cable Fly', 'Chest', null, 0),
  ('Low to High Cable Fly', 'Chest', null, 0),
  ('Pin Press', 'Chest', 'Triceps', 0),
  ('Conventional Deadlift', 'Back', 'Legs', 0),
  ('Barbell Row', 'Back', null, 0),
  ('Dumbbell Row', 'Back', null, 0),
  ('Incline Lying Dumbbell Row', 'Back', null, 0),
  ('Pull-Up', 'Back', 'Biceps', 0),
  ('Chin-Up', 'Back', 'Biceps', 0),
  ('Lat Pulldown', 'Back', null, 0),
  ('Seated Cable Row', 'Back', null, 0),
  ('Overhead Press', 'Shoulders', null, 0),
  ('Seated Dumbbell Shoulder Press', 'Shoulders', null, 0),
  ('Arnold Press', 'Shoulders', null, 0),
  ('Lateral Raise', 'Shoulders', null, 0),
  ('Cable Lateral Raise', 'Shoulders', null, 0),
  ('Rear Delt Fly', 'Shoulders', null, 0),
  ('Cable Rear Delt Fly', 'Shoulders', null, 0),
  ('Face Pull', 'Shoulders', 'Back', 0),
  ('Barbell Shrug', 'Traps', null, 0),
  ('Dumbbell Shrug', 'Traps', null, 0),
  ('Cable Shrug', 'Traps', null, 0),
  ('Barbell Curl', 'Biceps', null, 0),
  ('Dumbbell Curl', 'Biceps', null, 0),
  ('Incline Dumbbell Curl', 'Biceps', null, 0),
  ('Hammer Curl', 'Biceps', null, 0),
  ('Barbell Preacher Curl', 'Biceps', null, 0),
  ('Dumbbell Preacher Curl', 'Biceps', null, 0),
  ('Cable Curl', 'Biceps', null, 0),
  ('Close-Grip Bench Press', 'Triceps', 'Chest', 0),
  ('Skull Crusher', 'Triceps', null, 0),
  ('Cable Pushdown', 'Triceps', null, 0),
  ('Overhead Triceps Extension', 'Triceps', null, 0),
  ('Assisted Dip', 'Triceps', 'Chest', 0),
  ('Tricep Pin Press', 'Triceps', 'Chest', 0),
  ('Back Squat', 'Legs', null, 0),
  ('Front Squat', 'Legs', null, 0),
  ('Leg Press', 'Legs', null, 0),
  ('Romanian Deadlift', 'Legs', 'Back', 0),
  ('Hip Thrust', 'Legs', null, 0),
  ('Bulgarian Split Squat', 'Legs', null, 0),
  ('Walking Lunge', 'Legs', null, 0),
  ('Leg Extension', 'Legs', null, 0),
  ('Leg Curl', 'Legs', null, 0),
  ('Standing Calf Raise', 'Legs', null, 0),
  ('Seated Calf Raise', 'Legs', null, 0),
  ('Weighted Plank', 'Core', null, 0),
  ('Cable Crunch', 'Core', null, 0),
  ('Hanging Leg Raise', 'Core', null, 0),
  ('Ab Wheel Rollout', 'Core', null, 0),
  ('Decline Sit-Up', 'Core', null, 0),
  ('Pallof Press', 'Core', null, 0),
  ('Wrist Curl', 'Forearms', null, 0),
  ('Reverse Wrist Curl', 'Forearms', null, 0)
on conflict (name) do update set
  primary_muscle = excluded.primary_muscle,
  secondary_muscle = excluded.secondary_muscle,
  is_strength_exercise = 0;
