create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  primary_muscle text not null,
  secondary_muscle text,
  is_strength_exercise integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_date date not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_id bigint not null references public.workout_sessions(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  set_number integer not null,
  reps integer not null,
  weight numeric not null,
  rir numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.body_weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  weight numeric not null,
  logged_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, logged_date)
);

create table if not exists public.muscle_strength_config (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  muscle_group text not null,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  weight_factor numeric not null default 1.0
);

create table if not exists public.app_settings (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;
alter table public.body_weight_logs enable row level security;
alter table public.muscle_strength_config enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "profiles are visible to their owner" on public.profiles;
drop policy if exists "profiles can be inserted by their owner" on public.profiles;
drop policy if exists "profiles can be updated by their owner" on public.profiles;
drop policy if exists "exercises are owned by their user" on public.exercises;
drop policy if exists "workout sessions are owned by their user" on public.workout_sessions;
drop policy if exists "workout sets are owned by their user" on public.workout_sets;
drop policy if exists "body weight logs are owned by their user" on public.body_weight_logs;
drop policy if exists "muscle configs are owned by their user" on public.muscle_strength_config;
drop policy if exists "settings are owned by their user" on public.app_settings;

create policy "profiles are visible to their owner" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles can be inserted by their owner" on public.profiles
  for insert with check (auth.uid() = id);

create policy "profiles can be updated by their owner" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "exercises are owned by their user" on public.exercises
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sessions are owned by their user" on public.workout_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sets are owned by their user" on public.workout_sets
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "body weight logs are owned by their user" on public.body_weight_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "muscle configs are owned by their user" on public.muscle_strength_config
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "settings are owned by their user" on public.app_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists exercises_user_id_idx on public.exercises(user_id);
create index if not exists workout_sessions_user_id_date_idx on public.workout_sessions(user_id, workout_date desc);
create index if not exists workout_sets_user_id_created_idx on public.workout_sets(user_id, created_at, set_number);
create index if not exists workout_sets_session_id_idx on public.workout_sets(session_id);
create index if not exists workout_sets_exercise_id_idx on public.workout_sets(exercise_id);
create index if not exists body_weight_logs_user_id_date_idx on public.body_weight_logs(user_id, logged_date desc);

create or replace function public.profile_exists_for_email(lookup_email text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where lower(email) = lower(lookup_email)
  );
$$;

grant execute on function public.profile_exists_for_email(text) to anon, authenticated;
