create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  primary_muscle text not null,
  secondary_muscle text,
  is_strength_exercise integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.user_exercise_preferences (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  enabled integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, exercise_id)
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_date date not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_id bigint not null references public.workout_sessions(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  set_number integer not null,
  reps integer not null,
  weight numeric not null,
  rir numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.body_weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  weight numeric not null,
  logged_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, logged_date)
);

create table if not exists public.muscle_strength_config (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  muscle_group text not null,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  weight_factor numeric not null default 1.0
);

create table if not exists public.app_settings (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.user_exercise_preferences enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;
alter table public.body_weight_logs enable row level security;
alter table public.muscle_strength_config enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "profiles are visible to their owner" on public.profiles;
drop policy if exists "profiles can be inserted by their owner" on public.profiles;
drop policy if exists "profiles can be updated by their owner" on public.profiles;
drop policy if exists "exercises are owned by their user" on public.exercises;
drop policy if exists "standard exercises are readable by authenticated users" on public.exercises;
drop policy if exists "exercise preferences are owned by their user" on public.user_exercise_preferences;
drop policy if exists "workout sessions are owned by their user" on public.workout_sessions;
drop policy if exists "workout sets are owned by their user" on public.workout_sets;
drop policy if exists "body weight logs are owned by their user" on public.body_weight_logs;
drop policy if exists "muscle configs are owned by their user" on public.muscle_strength_config;
drop policy if exists "settings are owned by their user" on public.app_settings;

create policy "profiles are visible to their owner" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles can be inserted by their owner" on public.profiles
  for insert with check (auth.uid() = id);

create policy "profiles can be updated by their owner" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "standard exercises are readable by authenticated users" on public.exercises
  for select using (auth.role() = 'authenticated');

create policy "exercise preferences are owned by their user" on public.user_exercise_preferences
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sessions are owned by their user" on public.workout_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout sets are owned by their user" on public.workout_sets
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "body weight logs are owned by their user" on public.body_weight_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "muscle configs are owned by their user" on public.muscle_strength_config
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "settings are owned by their user" on public.app_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop index if exists exercises_user_id_idx;
create unique index if not exists exercises_name_idx on public.exercises(name);
create index if not exists user_exercise_preferences_user_id_idx on public.user_exercise_preferences(user_id);
create index if not exists user_exercise_preferences_exercise_id_idx on public.user_exercise_preferences(exercise_id);
create index if not exists workout_sessions_user_id_date_idx on public.workout_sessions(user_id, workout_date desc);
create index if not exists workout_sets_user_id_created_idx on public.workout_sets(user_id, created_at, set_number);
create index if not exists workout_sets_session_id_idx on public.workout_sets(session_id);
create index if not exists workout_sets_exercise_id_idx on public.workout_sets(exercise_id);
create index if not exists body_weight_logs_user_id_date_idx on public.body_weight_logs(user_id, logged_date desc);

create or replace function public.profile_exists_for_email(lookup_email text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where lower(email) = lower(lookup_email)
  );
$$;

grant execute on function public.profile_exists_for_email(text) to anon, authenticated;

grant select on public.exercises to authenticated;
grant select, insert, update, delete on public.user_exercise_preferences to authenticated;

insert into public.exercises (name, primary_muscle, secondary_muscle, is_strength_exercise) values
  ('Barbell Bench Press', 'Chest', null, 0),
  ('Incline Barbell Bench Press', 'Chest', null, 0),
  ('Dumbbell Bench Press', 'Chest', null, 0),
  ('Incline Dumbbell Press', 'Chest', null, 0),
  ('Machine Chest Press', 'Chest', null, 0),
  ('Weighted Dip', 'Chest', 'Triceps', 0),
  ('Cable Fly', 'Chest', null, 0),
  ('Conventional Deadlift', 'Back', 'Legs', 0),
  ('Barbell Row', 'Back', null, 0),
  ('Dumbbell Row', 'Back', null, 0),
  ('Pull-Up', 'Back', 'Biceps', 0),
  ('Chin-Up', 'Back', 'Biceps', 0),
  ('Lat Pulldown', 'Back', null, 0),
  ('Seated Cable Row', 'Back', null, 0),
  ('Overhead Press', 'Shoulders', null, 0),
  ('Seated Dumbbell Shoulder Press', 'Shoulders', null, 0),
  ('Arnold Press', 'Shoulders', null, 0),
  ('Lateral Raise', 'Shoulders', null, 0),
  ('Rear Delt Fly', 'Shoulders', null, 0),
  ('Face Pull', 'Shoulders', 'Back', 0),
  ('Barbell Curl', 'Biceps', null, 0),
  ('Dumbbell Curl', 'Biceps', null, 0),
  ('Incline Dumbbell Curl', 'Biceps', null, 0),
  ('Hammer Curl', 'Biceps', null, 0),
  ('Preacher Curl', 'Biceps', null, 0),
  ('Cable Curl', 'Biceps', null, 0),
  ('Close-Grip Bench Press', 'Triceps', 'Chest', 0),
  ('Skull Crusher', 'Triceps', null, 0),
  ('Cable Pushdown', 'Triceps', null, 0),
  ('Overhead Triceps Extension', 'Triceps', null, 0),
  ('Assisted Dip', 'Triceps', 'Chest', 0),
  ('Back Squat', 'Legs', null, 0),
  ('Front Squat', 'Legs', null, 0),
  ('Leg Press', 'Legs', null, 0),
  ('Romanian Deadlift', 'Legs', 'Back', 0),
  ('Hip Thrust', 'Legs', null, 0),
  ('Bulgarian Split Squat', 'Legs', null, 0),
  ('Walking Lunge', 'Legs', null, 0),
  ('Leg Extension', 'Legs', null, 0),
  ('Leg Curl', 'Legs', null, 0),
  ('Standing Calf Raise', 'Legs', null, 0),
  ('Seated Calf Raise', 'Legs', null, 0),
  ('Weighted Plank', 'Core', null, 0),
  ('Cable Crunch', 'Core', null, 0),
  ('Hanging Leg Raise', 'Core', null, 0),
  ('Ab Wheel Rollout', 'Core', null, 0),
  ('Decline Sit-Up', 'Core', null, 0),
  ('Pallof Press', 'Core', null, 0)
on conflict (name) do update set
  primary_muscle = excluded.primary_muscle,
  secondary_muscle = excluded.secondary_muscle,
  is_strength_exercise = 0;
